# Token de autenticacion
huggingface_token: "xxxxxxxxxxxxxxxxxxxxxxx"

# Ruta para salvar imagenes ejemplo
output_path: "./output"
samples_to_save: 3

# Ruta para salvar imagenes ejemplo
results: "./results"

# Dataset
dataset_name: "gymprathap/Breast-Cancer-Ultrasound-Images-Dataset"

# Modelo
model_name: "facebook/deit-base-patch16-224"

# Hiperparametros
batch_size: 16
num_epochs: 5
learning_rate: 2e-5

# Mlflow
tracking_url: http://localhost:5000
